# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build Maui.NET windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        source-url: https://nuget.pkg.github.com/YkeSmit1/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}   
    - name: Install .Net MAUI
      run: dotnet workload install maui      
    - name: Build
      run: dotnet publish maui.bidtrainer\maui.bidtrainer.csproj -c Release -f net9.0-windows10.0.19041.0 -p:RuntimeIdentifierOverride=win10-x64 --self-contained true -p:PublishReadyToRun=false
    - name: test c# test
      run: dotnet test .\BidTrainerTests\BidTrainerTests.csproj -c Release --no-restore
    - name: basictest c# basictest
      run: dotnet test .\Engine.DotNet.Tests\Engine.DotNet.Tests.csproj -c Release --no-restore
    - name: NuGet Restore
      run: nuget restore Maui.BidTrainer.sln
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: distribute_bidtrainer_windows
        path: ./**/*.msix
